### ISSUE TITLE
Similar items overflow

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/resell-react-native#100]
Observe when there are more than 3 similar items for a listing the items overflow, and there is no way to scroll horizontally:
![image](https://github.com/cuappdev/resell-react-native/assets/22649594/273f2d41-bb6c-487d-86c3-a42ef245e71b)

If we want more than 3 similar items we should probably arrange the images in a 3 by n grid. Alternatively, we can limit to 3 similar items on backend

**Comment by vinnie4k** [comment]
I did some testing and it turns out that it is scrollable, but because the images are tappable, it's unable to detect a scroll. If you click on a certain spot you'll be able to scroll.
