### ISSUE TITLE
Chat message subheading

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#102]
I don't think it's necessary to have the name of the person in the subheading of the chat since it is a 1:1 chat. We should do we iMessage and Instagram do and have just the message.

![image](https://github.com/cuappdev/resell-react-native/assets/75594943/1f9cddf6-f55b-4aa7-bffa-3a7da49c7ad7)

**Comment by zachseidner1** [comment]
what about when they send images or availability? If it just says [Image] it could be unclear what the latest chat history is

**Comment by vinnie4k** [comment]
> what about when they send images or availability? If it just says [Image] it could be unclear what the latest chat history is

"Attachment: 1 image" might be good enough or something.
