### ISSUE TITLE
Screens re-mounting on every navigation

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/resell-react-native#103]
https://github.com/cuappdev/resell-react-native/assets/22649594/9688b8cd-8e6e-4f67-8809-052c07b496a6

The bookmarks and chat screens appear to be re-loading data every time I navigate to them, which causes the text to constantly jitter when I first navigate to the screen due to the data having to be loaded in each time. You can see how this compares to the Home Screen in the video above, which does not change its data on navigation and thus does not jitter.

My guess is that this is a result of wanting to display the most updated chats and bookmarks to the user, hence the constant re-loading of data. This puts unnecessary strain on our server, worsens UX for users with poor internet connections, and causes the jitters in the video above. In the long term if we plan to build more features requiring realtime updates we should use something like [Sockets](https://socket.io) in order to receive an event on the frontend from the server whenever a particular screen needs to be refreshed.

In the short term, we should be able to maintain the latest bookmarks through global state maintained via Redux, and since the chat is implemented using firebase, we only need to refresh that screen when firebase records a message has been sent. This should eliminate the need to constantly ping the server to load the page after it initially mounts.

**Comment by vinnie4k** [comment]
The listing images seem to flicker many times when I tap on the profile page.

https://github.com/cuappdev/resell-react-native/assets/75594943/3b651ca0-fab5-439d-b3f6-658588ce030a
