### ISSUE TITLE
Homepage elements reordering

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/resell-react-native#107]
Performing certain actions like bookmarking appears to (sometimes) reorder items on the home screen in an unpredictable way. This could be annoying if there are a lot of listings and someone is attempting to scroll through then but they keep reordering:

https://github.com/cuappdev/resell-react-native/assets/22649594/fef9babc-652e-4723-9bb9-2c23d5d514c9

I believe this is due to the same issue as #103, because we're re-loading screens on certain events like bookmarks. Even if we maintain the current architecture and don't switch to sockets, I don't see why the homepage would have to change when a user bookmarks an item, so this functionality should be removed. (unless something else is causing this behavior)

**Comment by nancykduong** [comment]
this can be addressed post-launch but if we can do pre-launch that would be nice

**Comment by zachseidner1** [comment]
fair, this should be a small fix so I'll move this to pre-launch.
