### ISSUE TITLE
Home page filters cut off

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#109]
When we scroll horizontally on the home page filters, the right edge is not cut off but the left is.

![Simulator Screenshot - iPhone 15 Pro - 2024-03-15 at 20 43 55](https://github.com/cuappdev/resell-react-native/assets/75594943/b9ae4c04-6cfb-466b-8de2-48f83fceee2f)

**Comment by zachseidner1** [comment]
Same component as in #125
