### ISSUE TITLE
Price input buttons

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/resell-react-native#113]
It's difficult to tap on the numbers when the price input modal pops up when negotiating price, it seems like there's a lot of whitespace between buttons (I believe the same component is used for other price inputs as well). It'd be nice to just remove all whitespace and then make the number buttons TouchableOpacities or have a gray background when tapped so it's more clear what's being tapped on

**Comment by vinnie4k** [comment]
+1 it was very annoying to use.
