### ISSUE TITLE
Hard to dismiss availability modal

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/resell-react-native#114]
![image](https://github.com/cuappdev/resell-react-native/assets/22649594/be8ecff5-7a66-48a7-bda8-32fcc5fe21f3)
The only way to dismiss this modal is to tap between the top of the screen and the top of the modal, which is especially hard to do on iPhones X and above due to the front cameras (not shown in screenshot) -- it'd be nice to be able to drag the modal down from the top

**Comment by vinnie4k** [comment]
Mentioned in #62.
