### ISSUE TITLE
Add the ability to block users (required by Apple)

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#117]
Title. Plus, we should have a page in settings to view all blocked users and unblock them. There's also a lot of edge cases that we need to think about when developing this such as clearing already saved bookmarks of a blocked user. What happens when we unblock? Do these come back or are they gone forever? Is the user that is BEING BLOCKED able to see the user that has them blocked?

**Comment by Archit404Error** [comment]
+1, another Apple required feature is the ability to delete profiles -- once again, we should determine what will happen to users' chats with other users who have deleted profiles, bookmarked posts from deleted users, etc.
