### ISSUE TITLE
EULA

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#118]
In the onboarding flow, we should display the EULA and have a link where they can view it. Users MUST agree to it in order to create an account. See the screenshot below of an app that I worked on and how it displays this. Additionally, we should be able to view the EULA in settings as well as our Privacy Policy.

<img width="325" alt="image" src="https://github.com/cuappdev/resell-react-native/assets/75594943/c6133e57-21f2-49ea-9493-f4e3d1dba847">

**Comment by nancykduong** [comment]
in designs
