### ISSUE TITLE
Flagging content

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#119]
Add the ability to flag objectionable content such as chat messages, listings, etc. According to Apple, "the developer must act on objectionable content reports within 24 hours by removing the content and ejecting the user who provided the offending content."

**Comment by zachseidner1** [comment]
do you think just having the ability to report / block users would satisfy this? Or do you think we would have to add reporting to all content on Resell?

**Comment by vinnie4k** [comment]
> do you think just having the ability to report / block users would satisfy this? Or do you think we would have to add reporting to all content on Resell?

All content as well.
