### ISSUE TITLE
Asking for username and bio even though already set

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#121]
I never went through and specified a username or bio, but when I exit the flow, I was able to bypass that page and it looks like a username was auto created for me (kind of mentioned in #56) . When I log out, it asks me for it again.

https://github.com/cuappdev/resell-react-native/assets/75594943/12b545fd-0ddd-4d45-bb06-4c91779422a4

**Comment by zachseidner1** [comment]
I feel like this is more of an edge case and something we can address after launch, do you agree?

**Comment by nancykduong** [comment]
yea this can be addressed post-launch
