### ISSUE TITLE
Add deleting user profiles (Apple mandated)

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/resell-react-native#128]
I'm making this a separate issue because it's quite important to implement this prior to launch -- as mentioned in the comments of #117, another Apple required feature is the ability to delete profiles -- we should determine what will happen to users' chats with other users who have deleted profiles, bookmarked posts from deleted users, etc.

I know this is implemented on backend already but we should probably change it to a soft delete for safety purposes

**Comment by nancykduong** [comment]
design completed
