### ISSUE TITLE
Calendars being created in Apple Calendar

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#131]
I just checked my Apple calendar and see a bunch of "Resell Appointments" calendars.

<img width="180" alt="image" src="https://github.com/cuappdev/resell-react-native/assets/75594943/44bd9b3f-d085-44e2-b974-5e38ccb599f1">

**Comment by zachseidner1** [comment]
I think this is intended behavior if you confirm a meeting? But it just came up without you taking that action I assume?

**Comment by vinnie4k** [comment]
> I think this is intended behavior if you confirm a meeting? But it just came up without you taking that action I assume?

Not sure if I confirmed it at all. It just showed up but the main problem is that it creates a whole new calendar instead of an event which is clogging up my Apple calendar.

**Comment by zachseidner1** [comment]
> > I think this is intended behavior if you confirm a meeting? But it just came up without you taking that action I assume?
> 
> Not sure if I confirmed it at all. It just showed up but the main problem is that it creates a whole new calendar instead of an event which is clogging up my Apple calendar.

Gotcha, I think there is some code that was creating calendars for debugging purposes that hasn't been removed yet. I'll look into creating an event instead of a calendar though.
