### ISSUE TITLE
Share and report has overflowing bottom edge

### ISSUE THREAD

**Issue by zachseidner1** [cuappdev/resell-react-native#139]
On item details screen
<img width="272" alt="image" src="https://github.com/cuappdev/resell-react-native/assets/58796478/9d3b9f5c-c2bb-417f-b0f3-dfed0d0e890b">

**Comment by nancykduong** [comment]
is this a quick fix? just to make the ui a bit cleaner for launch?

**Comment by zachseidner1** [comment]
should be
