### ISSUE TITLE
Persist Storage

### ISSUE THREAD

**Issue by Haichen-Wang** [cuappdev/resell-react-native#19]
Currently, notification preferences of settings uses redux but the change will not persist when an app is destroyed. Refactoring using [redux persist](https://github.com/rt2zz/redux-persist) is needed to save user's preferences for the long run. Or alternatively, the settings can be saved on the server for future retrieval.

**Comment by zachseidner1** [comment]
@vinnie4k any reason you closed this? This is still a relevant issue in the app.

**Comment by vinnie4k** [comment]
> @vinnie4k any reason you closed this? This is still a relevant issue in the app.

Oh I thought we had persistence working. In that case, we can just keep this issue open.

**Comment by zachseidner1** [comment]
> > @vinnie4k any reason you closed this? This is still a relevant issue in the app.
> 
> 
> 
> Oh I thought we had persistence working. In that case, we can just keep this issue open.

Persistence works, but not for notification settings, which is what this issue is pointing out.
