### ISSUE TITLE
Sharing functionality sends an unclickable link

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#52]
![image](https://github.com/cuappdev/resell-react-native/assets/75594943/ea89a811-29ea-4956-bb56-bb4ccefa24ac)

**Comment by nancykduong** [comment]
can you make it so that there's an image that's sent with the link, similar to how figma does it? design will make a design for it <3
![image](https://github.com/cuappdev/resell-react-native/assets/142942906/2da83528-78cc-47bc-be3f-699a954e590b)

**Comment by rs929** [comment]
Duplicate of #82
