### ISSUE TITLE
Truncating for price input

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#72]
Should we truncate "6.0" to just "6" when entering the price? I also noticed that "0.7" becomes ".7". Can we make it sho "0.70"? It makes more sense to display prices this way.

https://github.com/cuappdev/resell-react-native/assets/75594943/80741e61-7e9c-41ef-a3eb-24b5514ec7cd

**Comment by rs929** [comment]
I made it so that prices are automatically converted to money format where two zeros are appended to the end of the decimal point depending on the amount entered, so typing in 6. or 6.0 would display "$6.00"

**Comment by vinnie4k** [comment]
> I made it so that prices are automatically converted to money format where two zeros are appended to the end of the decimal point depending on the amount entered, so typing in 6. or 6.0 would display "$6.00"

Nice. Let's also make sure that it restricts to 2 decimal places.
