### ISSUE TITLE
Able to use non-Cornell email

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#75]
We should restrict to just Cornell emails and have a popup if they try to use something else.

There is one email that we should whitelist (appstoreappdev@gmail.com). No need to test it. I’ll test it since Ihave the login.

https://github.com/cuappdev/resell-react-native/assets/75594943/a06fcb0a-bae2-451e-998d-72459d06fc88

**Comment by Archit404Error** [comment]
This is interesting, when I log in with a non cornell email it rejects the login but it'd be nice to have a better error message for the user:

https://github.com/cuappdev/resell-react-native/assets/22649594/20ff2a55-8587-4f77-b79c-56319a9c8207
