### ISSUE TITLE
No Image Access Requirement

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/resell-react-native#77]
Apple does not allow apps to "force" users to accept certain permissions, so a default photo should be set for the user profile if they refuse to allow access to photos:
![IMG_1837](https://github.com/cuappdev/resell-react-native/assets/22649594/770ea5ff-7aa7-4115-a840-eec289d0b05d)

(also gallery was misspelled)

**Comment by zachseidner1** [comment]
The user's Google PFP is default if they do not allow photo access. Is there anything else you're looking for us to fix with this issue? Do you want the Google PFP to show up there as default?

**Comment by Archit404Error** [comment]
Yeah that'd be a good idea to avoid surprising users, also the alert should either be removed or made more specific like "defaulting to google account profile picture"

**Comment by nancykduong** [comment]
richie in this case you can just have a pop up like the one in the photo that says like 

"Notice: If you do not add your own profile picture, it will default to your Google account profile picture."

**Comment by rs929** [comment]
I was able to fix this in my PR by only displaying a message when users deny Photo requirements, and click on a button or feature that requires them to upload an image. The alert gives them the option to cancel or navigate to the settings page to update the permissions if they change their mind

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-03-28 at 16 50 22](https://github.com/cuappdev/resell-react-native/assets/105038960/75aa2bf6-0838-4e5d-bd87-29b00d192395)
